---
- name: Launch a single instance of an EC2 and move text
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Start an EC2
      ec2:
        key_name: [which key? prob default]
        group: scraping-security-group
        instance_type: t2.micro
        image: ami-c229c0a2
        wait: true
        count: 1
        assign_public_ip: yes
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
    - name: Wait for SSH to come up
      wait_for: host{{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure scrapers
  hosts: launched
  become: True
  gather_facts: True
  yum: name=java state=absent
  yum: name=git state=latest

#- name: Terminate scrapers
#  hosts: localhost
#  connection: local
#  tasks:
#    - name: Terminate instances that were launched
#      ec2:
#        state: 'absent'
#        instance_ids '{{ ec2.instance_ids }}'
